# -*- coding: utf-8 -*-
"""data_types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8MYBye9pQYEEZFwRsf8uIyh7GTKaKPw
"""

Name ="Faith"
age = 19
height = 5.7
favourite_tech_field ="Data Engineering"
student_status = "Junior"
print(f"My name is {Name}, i am {age} years old, my height is {height}, i love {favourite_tech_field} and i am currently a {student_status} in college.")

Name ="John"
age =20
date = 29.05
number_of_family_members =5
is_this_correct = True

print(type(Name))
print(type(age))
print(type(date))
print(type(number_of_family_members))
print(type(is_this_correct))

#convert from float to int
y = int(5.69)
print(y)

#convert string number to integer
num_string ='56'
num_integer = 75

num_string = int(num_string)

num_sum =num_integer + num_string
print(f"sum: {num_sum}")

#convert interger to string
num_interger2 =87

num_string2 =str(num_interger2)

print(num_string2)
print(type(num_string2))

name =input("Enter your name: ")
age = int(input("Enter your age: "))
country = str(input("Enter your country: "))

print("\n-------------------------------------")
print("Generating Personalized Message")
print("\n-------------------------------------")

personalize_message =(f"Hello {name}, You are currently {age} . Also living in {country}" )

print(personalize_message)

print("/n ------------------Temperature Converter----------------")

celsius = float(input("Enter the temperature in celsius: "))

fahrenheit = (celsius * 9/5 )+ 32

print(f"The temparature of {celsius} C is equal to {fahrenheit} F")
